### ISSUE TITLE
add some documentation [WIP]

### ISSUE THREAD

**Issue by lordfiSh** [Craftoncu/hacs-vikunja-integration#29]
Hi, 
first thanks for creating this Addon, but this Addon needs some Documentation. I will list them here and may create a PR for the Readme later 

**What API Permission are needed?** 
If I just tick every Box in Tasks, that seems to be not enough

```
Something really wrong happened!
Traceback (most recent call last):
  File "/config/custom_components/hacs_vikunja_integration/api.py", line 95, in _api_wrapper
    raise HacsVikunjaIntegrationApiClientAuthenticationError(
custom_components.hacs_vikunja_integration.api.HacsVikunjaIntegrationApiClientAuthenticationError: Invalid credentials

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/hacs_vikunja_integration/config_flow.py", line 31, in async_step_user
    await self._test_credentials(
  File "/config/custom_components/hacs_vikunja_integration/config_flow.py", line 79, in _test_credentials
    await client.list_projects()
  File "/config/custom_components/hacs_vikunja_integration/api.py", line 48, in list_projects
    return await self._api_wrapper(method="get", url=url, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs_vikunja_integration/api.py", line 110, in _api_wrapper
    raise HacsVikunjaIntegrationApiClientError(
custom_components.hacs_vikunja_integration.api.HacsVikunjaIntegrationApiClientError: Something really wrong happened!
```

**What Version is needed?**
I had some old Version running, you need need at least Version 0.23.0, with the new API System

Where to find the To-do **lists**
Only found the new Todo Entities , but not the Tasks itself. Took a bit to find the new Item in the Navbar
![image](https://github.com/user-attachments/assets/248ee602-00a0-40cb-b0fb-9f0b4bc6c062)

and its using the new Home Assistant ToDo List Function, added in [2023.11.](https://www.home-assistant.io/integrations/todo/)

![image](https://github.com/user-attachments/assets/e978c50b-f21b-4193-93a0-589cc2adcb80)

** Can you use Automations? **
?

** Can you filter the Todo lists (closed, overdue...) **
?

**Comment by Craftoncu** [comment]
Hey, sorry. Ive seen this issue right now. My permissions on the vikuna side are like this: 
![image](https://github.com/user-attachments/assets/f6d95c79-9220-40b7-82fd-d3bb1d234bf4)

I stopped using vikunja, because we migrated to YouTrack. But im still open to help. Automations are not available except the ones which u can use for home assistant's todo lists. 

There is no filter available. It should only list undone tasks

**Comment by xJylin** [comment]
Question regarding home-assistants todo-list funtions.
I've seen code implementations for task deletion & creation. 
However it seems to be commented out.
Is there a specific reason for this?

**Comment by Craftoncu** [comment]
Yeah,
at first it was necessary for me to have the tasks updating. I stopped using the module - so thats why i stopped programming it further
